[package]
name = "arche"
version = "0.2.0"
edition = "2021"

[workspace]
members = [
  "basic_engine"
]

[dependencies]
lazy_static = "1.4.0"
regex = "1"
basic_engine = { path = "./basic_engine" }
rand = "0.8.5"

[profile.bench]
debug = true
