[package]
name = "arche"
version = "0.3.7"
edition = "2024"
rust-version = "1.85"
authors = [
  "Andrew Wright"
]

[workspace]
members = [
  "basic_engine"
]

[dependencies]
lazy_static = "1.5.0"
regex = "1"
basic_engine = { path = "./basic_engine" }
rand = "0.9.2"

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
debug = true
