[package]
name = "basic_engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[lib]
bench = false #https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options

[dependencies]
smallvec = "1.15.1"

[dev-dependencies]
proptest = "1.7"
criterion = "0.7"
pretty_assertions = "1.4"

[[bench]]
name = "benchmark"
harness = false
