#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2022-2026 Andrew Wright

"""Build the games suite: positions drawn from whole games, for `bench games`.

The engine plays itself from book openings to the end of each game, every
position after the book goes into one pool, and the suite is a uniform sample
of that pool, so a long game gives more positions than a short one. Why the
bench wants a second suite is in docs/DEVELOPMENT.md, under the games suite.

    python3 scripts/build_games.py <engine> <book.pgn> arche-core/games.epd --commit <sha>

The book is `scripts/book.sh fetch 8moves_v3 <dir>`. The engine plays each
move to a fixed node budget, so a given engine, book and seed rebuild the
same file. The committed file is not rebuilt to follow the engine: it is a
sample of positions, not a measure of the engine, and changing it changes
every number `bench games` has printed.
"""

import argparse
import random
import subprocess
import sys
from pathlib import Path

import chess
import chess.pgn

GAMES = 300
POSITIONS = 96
NODES_A_MOVE = 20_000
# games that run past this many plies after the book are cut there, well past
# where the clock matches' games end (about 130 plies)
MOST_PLIES = 300
SEED = 20260928

HEADER = """\
# The games suite: {positions} positions drawn uniformly from every position
# after the book in {games} games the engine played against itself, so the
# phases of a game are weighted as a game weights them. A game ends at mate,
# stalemate, a draw either side could claim, or {most} plies after the book,
# whichever comes first. Generated by
# scripts/build_games.py and not edited by hand, from
#
#   the engine at {commit}, {nodes} nodes a move, seed {seed}
#   book 8moves_v3, the pin scripts/book.sh names
#
# One position a line as a four field fen and an id naming the game and the
# ply after the book. The clocks are not part of it: every position is
# searched as if it had just arisen.
#
# `bench games` searches each to a fixed node budget. Changing a line changes
# every number it has printed, so add to the end rather than edit.
"""


class Engine:
    def __init__(self, path: str):
        self.process = subprocess.Popen(
            [path], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, bufsize=1
        )
        self.send("uci")
        self.send("isready")
        self.until("readyok")

    def send(self, line: str) -> None:
        assert self.process.stdin is not None
        self.process.stdin.write(line + "\n")
        self.process.stdin.flush()

    def until(self, prefix: str) -> str:
        assert self.process.stdout is not None
        for line in self.process.stdout:
            if line.startswith(prefix):
                return line
        raise RuntimeError(f"the engine closed before saying {prefix}")

    def best(self, moves: list[str], nodes: int) -> str:
        self.send("position startpos moves " + " ".join(moves))
        self.send(f"go nodes {nodes}")
        return self.until("bestmove").split()[1]

    def close(self) -> None:
        self.send("quit")
        self.process.wait()


def openings(book: Path) -> list[list[str]]:
    lines = []
    with book.open() as f:
        while (game := chess.pgn.read_game(f)) is not None:
            lines.append([move.uci() for move in game.mainline_moves()])
    return lines


def play(engine: Engine, opening: list[str], nodes: int) -> list[str]:
    """The fens after the book, one a ply, until the game ends."""
    board = chess.Board()
    moves = list(opening)
    for move in moves:
        board.push_uci(move)
    engine.send("ucinewgame")
    fens = []
    for _ in range(MOST_PLIES):
        if board.is_game_over(claim_draw=True):
            break
        fens.append(board.fen())
        move = engine.best(moves, nodes)
        board.push_uci(move)
        moves.append(move)
    return fens


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("engine")
    parser.add_argument("book", type=Path)
    parser.add_argument("out", type=Path)
    parser.add_argument(
        "--commit", required=True, help="the commit the engine was built from"
    )
    arguments = parser.parse_args()

    rng = random.Random(SEED)
    book = openings(arguments.book)
    chosen = rng.sample(range(len(book)), GAMES)
    engine = Engine(arguments.engine)
    pool = []
    for game, index in enumerate(chosen):
        for ply, fen in enumerate(play(engine, book[index], NODES_A_MOVE)):
            pool.append((game, ply, fen))
    engine.close()

    drawn = sorted(rng.sample(pool, POSITIONS))
    with arguments.out.open("w") as out:
        out.write(
            HEADER.format(
                positions=POSITIONS,
                games=GAMES,
                commit=arguments.commit,
                most=MOST_PLIES,
                nodes=NODES_A_MOVE,
                seed=SEED,
            )
        )
        for game, ply, fen in drawn:
            four = " ".join(fen.split()[:4])
            out.write(f'{four} id "game {game} ply {ply}";\n')
    print(f"{len(pool)} positions in {GAMES} games, {POSITIONS} drawn", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
