#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2022-2026 Andrew Wright

"""Convert the Strategic Test Suite to the epd the strategic suite reads.

The suite grades rather than passes or fails: each position carries ten moves
with a score out of a hundred, and a position is worth what the move the
search settles on is worth. The source names those moves twice, once in san
and once in the coordinate notation the engine already speaks, so the
conversion is a matter of keeping the right column and no san parser or
python-chess is needed here.

    python3 scripts/build_strategy.py STS1-STS15_LAN_v5.epd arche-core/strategy.epd

The source is pinned below at a commit and by its checksum, because that
repository revises positions on its default branch, and the checksum is
written into the header of what this produces. It is not rerun to refresh the
committed file, though: a suite that is already gating on a number is added to
rather than rebuilt, for the reason its own header gives.

Everything that will not read raises rather than being skipped. The result is
committed and gates a build, so a line nobody is sure of is worth less than no
file at all.
"""

import argparse
import hashlib
import re
import sys
from collections.abc import Iterator
from pathlib import Path

# The Strategic Test Suite, fifteen themes of a hundred positions, in the copy
# fsmosca/STS-Rating publishes. Version five is the one taken: it scores ten
# moves where version three scores four, so the engine's move is usually
# somewhere on the scale and the total moves smoothly rather than snapping to
# zero, and grading already handles a position with two nearly equal moves,
# which is what version six's filter exists to remove.
SOURCE_URL = (
    "https://raw.githubusercontent.com/fsmosca/STS-Rating/{ref}"
    "/epd/STS1-STS15_LAN_v5.epd"
)
SOURCE_REF = "4e36977090c3a93ea57d5f34e13e42df422634d3"
SOURCE_SHA256 = "471ce06a56670ee7994f717790b91a9d47143bc40ce600c9eb91f4b53739d7be"

# The themes the source carries and how many positions each holds. Named
# rather than counted, so a source that has been revised under the pin, or a
# neighbouring file handed over by mistake, fails here instead of producing a
# suite that looks like this one and is not.
THEMES = {
    "Undermine": 100,
    "Open Files and Diagonals": 100,
    "Knight Outposts/Repositioning/Centralization": 100,
    "Square Vacancy": 100,
    "Bishop vs Knight": 100,
    "Recapturing": 100,
    "Offer of Simplification": 100,
    "AKPC": 100,
    "Advancement of a/b/c pawns": 100,
    "Simplification": 100,
    "King Activity": 100,
    "Center Control": 100,
    "Pawn Play in the Center": 100,
    "7th Rank": 100,
    "AT": 100,
}

# One line of the third theme spells it with the last two words the other way
# round. Both spellings mean the theme, and a report that grouped by the name
# as written would print it twice, so the odd one out is folded into the
# spelling the other ninety nine use. It is the only edit made to a theme
# name: two of them are abbreviated in the source, AKPC and AT, and are left
# as the source writes them, because expanding them would be a guess.
SPELLINGS = {
    "Knight Outposts/Centralization/Repositioning": (
        "Knight Outposts/Repositioning/Centralization"
    ),
}

# `STS(v1.0) Undermine.001`. The version tag goes with exactly one theme, so
# it says nothing the theme does not; it comes off, and that it says nothing
# is checked rather than assumed.
IDENTIFIER = re.compile(r"^STS\((?P<tag>v[\d.]+)\)\s+(?P<name>\S.*?)\.(?P<number>\d+)$")

# The coordinate notation the engine speaks: two squares and an optional
# promotion piece.
MOVE = re.compile(r"^[a-h][1-8][a-h][1-8][qrbn]?$")

HEADER = """\
# The Strategic Test Suite, fifteen themes of a hundred positions each, with
# every position's graded moves in the coordinate notation the engine speaks.
# Generated by scripts/build_strategy.py from
#
#   {url}
#
# and not edited by hand. It is pinned at a commit and by its checksum,
#
#   sha256 {sha256}
#
# because the repository it comes from revises positions on its default
# branch.
#
# That file is under the MIT licence, which asks that the notice travel with
# the work, so it does:
#
#   Copyright (c) 2019 fsmosca
#
#   Permission is hereby granted, free of charge, to any person obtaining a
#   copy of this software and associated documentation files (the
#   "Software"), to deal in the Software without restriction, including
#   without limitation the rights to use, copy, modify, merge, publish,
#   distribute, sublicense, and/or sell copies of the Software, and to permit
#   persons to whom the Software is furnished to do so, subject to the
#   following conditions:
#
#   The above copyright notice and this permission notice shall be included
#   in all copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
#   NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
#   DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
#   OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
#   USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# The scores are a Stockfish 15 analysis of sixty seconds a position at
# multipv 10, which the source records line by line and is recorded here once.
#
# One position a line, as a four field fen followed by a bm operation holding
# the highest scoring move, or every one of them where several share the top
# score, an id operation naming the theme and the position within it, and a
# points operation holding every graded move with its score.
# The clocks are not part of it: every position is searched as if it had just
# arisen.
#
# A position is worth what the move the search settles on is worth, and
# nothing when that move is not one of the graded ones, so this suite says how
# good an answer was where the tactical one says whether it was the answer.
# Where several moves share the top score, bm names all of them, the way a
# tactical position with two ways to win does.
#
# Changing a line changes every total this suite has ever printed,
# so add to the end rather than edit.
"""


# The three readers below are scripts/build_tactics.py's, copied rather than
# imported: that script reads san and so imports python-chess at the top, and
# importing it here would make this script need a library it has no use for
# and that ci does not install. `operations_of` differs anyway, since the
# quotes come off an operand here.
def split_operations(text: str) -> list[str]:
    """The `;` separated operations of an epd line, with the separators inside
    a quoted operand left alone."""
    operations = []
    current = ""
    quoted = False
    for character in text:
        if character == '"':
            quoted = not quoted
        if character == ";" and not quoted:
            operations.append(current)
            current = ""
        else:
            current += character
    operations.append(current)
    return [operation.strip() for operation in operations if operation.strip()]


def operations_of(text: str) -> dict[str, str]:
    """The operations of an epd line as opcode to operand, with the quotes
    around an operand taken off.

    An opcode twice on one line raises rather than taking the last of them.
    A second `c9` would quietly convert the wrong ten moves and a second `c8`
    would quietly rescore them, and neither line is one to guess at.
    """
    found = {}
    for operation in split_operations(text):
        opcode, _, operand = operation.partition(" ")
        if opcode in found:
            raise ValueError(f"{opcode} appears twice")
        found[opcode] = operand.strip().strip('"')
    return found


def positions(text: str) -> Iterator[tuple[int, str, dict[str, str]]]:
    """Yield `(line number, four field fen, operations)` for every position in
    an epd file, skipping comments and blank lines."""
    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split(None, 4)
        if len(fields) < 4:
            raise ValueError(f"line {number}: not an epd position: {line}")
        try:
            operations = operations_of(fields[4]) if len(fields) > 4 else {}
        except ValueError as error:
            raise ValueError(f"line {number}: {error}") from error
        yield number, " ".join(fields[:4]), operations


def graded_moves(number: int, operations: dict[str, str]) -> list[tuple[str, int]]:
    """The `c9` moves paired with their `c8` scores, in the source's order.

    The two are separate operations holding separate lists, so everything
    that could have them disagree is checked: their lengths, that a score is
    a whole number the suite's hundred covers, that a move is a move, and that
    no move is graded twice.
    """
    for opcode in ("c8", "c9"):
        if not operations.get(opcode):
            raise ValueError(f"line {number}: no {opcode} operation")
    scores = operations["c8"].split()
    moves = operations["c9"].split()
    if len(scores) != len(moves):
        raise ValueError(
            f"line {number}: {len(moves)} moves in c9 and {len(scores)} "
            f"scores in c8, which cannot be paired"
        )
    for move in moves:
        if not MOVE.match(move):
            raise ValueError(f"line {number}: {move} is not a coordinate move")
    if len(set(moves)) != len(moves):
        raise ValueError(f"line {number}: a move is graded twice in c9")
    graded = []
    for move, score in zip(moves, scores):
        if not re.fullmatch(r"\d+", score) or not 1 <= int(score) <= 100:
            raise ValueError(
                f"line {number}: {score} is not a score, which is a whole "
                f"number from one to a hundred"
            )
        graded.append((move, int(score)))
    return graded


def identify(number: int, operations: dict[str, str]) -> tuple[str, str, str]:
    """The `(version tag, theme, position number)` of a line's id, with the
    theme spelt the way the rest of its theme spells it."""
    identifier = operations.get("id")
    if not identifier:
        raise ValueError(f"line {number}: no id operation")
    match = IDENTIFIER.match(identifier)
    if not match:
        raise ValueError(f"line {number}: {identifier} is not an STS id")
    theme = SPELLINGS.get(match.group("name"), match.group("name"))
    return match.group("tag"), theme, match.group("number")


def convert(text: str, expected: dict[str, int] | None = None) -> list[str]:
    """Convert the source suite to epd lines the engine can read.

    Each line keeps its fen, names its highest scoring move in bm, and carries
    every graded move with its score in a points operation. What the source
    said twice is dropped: `c0` and `c7` are the same moves in san, `c8` and
    `c9` are now in points, and `Ae` names the analysis the header names.
    """
    expected = THEMES if expected is None else expected
    converted = []
    tags: dict[str, str] = {}
    counted: dict[str, int] = {}
    named: set[tuple[str, str]] = set()
    for number, fen, operations in positions(text):
        graded = graded_moves(number, operations)
        tag, theme, position = identify(number, operations)
        if tags.setdefault(tag, theme) != theme:
            raise ValueError(
                f"line {number}: {tag} names both {tags[tag]} and {theme}, so "
                f"the theme alone does not say which positions these are"
            )
        if (theme, position) in named:
            raise ValueError(f"line {number}: {theme}.{position} is named twice")
        named.add((theme, position))
        counted[theme] = counted.get(theme, 0) + 1
        top = max(score for _, score in graded)
        best = " ".join(move for move, score in graded if score == top)
        points = " ".join(f"{move}={score}" for move, score in graded)
        converted.append(
            f'{fen} bm {best}; id "{theme}.{position}"; points "{points}";'
        )
    if counted != expected:
        raise ValueError(
            f"the source holds {sorted(counted.items())}, not the "
            f"{sorted(expected.items())} this suite is"
        )
    return converted


def shared_tops(lines: list[str]) -> list[str]:
    """The ids of the converted lines whose top score is shared, which is a
    thing about the source worth printing rather than passing over."""
    shared = []
    for line in lines:
        operations = operations_of(line.split(None, 4)[4])
        if len(operations["bm"].split()) > 1:
            shared.append(operations["id"])
    return shared


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="the epd suite to convert")
    parser.add_argument("output", type=Path, help="path of the epd file to write")
    args = parser.parse_args(argv)

    raw = args.source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(
            f"{args.source} is sha256 {digest}, not the pinned "
            f"{SOURCE_SHA256}: the header would state a checksum this file "
            f"does not have"
        )
    converted = convert(raw.decode("utf-8"))
    header = HEADER.format(url=SOURCE_URL.format(ref=SOURCE_REF), sha256=SOURCE_SHA256)
    args.output.write_text(
        header + "".join(f"{line}\n" for line in converted),
        encoding="utf-8",
        newline="\n",
    )
    shared = shared_tops(converted)
    print(f"wrote {len(converted)} positions to {args.output}")
    print(f"{len(shared)} of them share their top score between several moves")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
