#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2022-2026 Andrew Wright

"""Convert a published tactical suite to the notation the engine speaks.

Published suites name their best moves in san: `Rxb2`, `Ra8#`, `O-O`. San
cannot be read without a board, because `Rxb2` does not say which rook. The
engine speaks coordinate notation, `a1b2` and `e7e8q`, and has no san parser,
and writing one means the disambiguation rules, the check and mate suffixes,
castling and promotion, every one of them easy to get subtly wrong for a file
that is read once. So the conversion happens here, once, with python-chess,
and its result is committed: ci then needs neither the network nor python to
run the suite.

    python3 scripts/build_tactics.py wac.epd arche-core/tactics.epd

The source is pinned below at a commit rather than named by a branch, so what
this produced can be produced again. It is not rerun to refresh the committed
file, though: a suite that is already gating on a number is added to rather
than rebuilt, for the reason its own header gives.
"""

import argparse
import sys
from collections.abc import Iterator
from pathlib import Path

import chess

# Win At Chess, Fred Reinfeld's 300 tactical positions, in the epd encoding
# that has been passed around since the 1990s. This copy has not changed since
# 2004 and its fens and bm moves agree move for move with the copies in
# pd/benthos and dimock/chess, which were checked against it rather than
# trusted.
SOURCE_URL = "https://github.com/jwiegley/emacs-chess/blob/{ref}/wac.epd"
SOURCE_REF = "9605600c114e3981b3c2e30d4e39c8f032a64c3d"

# The two operations kept. `bm` is the suite, and `id` is what a failure names
# the position by, which is the difference between a report that can be looked
# up and a count.
#
# Everything else is dropped. The suite as published carries `acd`, `acn`,
# `acs`, `ce` and `pv` on some lines: the depth, node count, seconds, score
# and principal variation of one run of one engine from 2004. They describe
# that engine rather than the position, nothing here reads them, and a stale
# score sitting beside a position would sooner or later be read as a target.
KEPT = ("bm", "id")

HEADER = """\
# Win At Chess, the 300 position tactical suite, with each position's best
# moves in the coordinate notation the engine speaks. Generated by
# scripts/build_tactics.py from
#
#   {url}
#
# and not edited by hand. The suite names its moves in san, which cannot be
# read without a board, so the conversion is done once in python rather than
# in an engine that would need a san parser to do it.
#
# One position a line, as a four field fen followed by a bm operation holding
# every move that counts as solving it and an id operation naming it, which is
# the epd form bench.epd uses. The clocks are not part of it: every position is
# searched as if it had just arisen. A position is solved when the move the
# search settles on is one of the bm moves, so a line with several of them
# accepts any of the several.
#
# The operations the source carried that nothing here reads are dropped: acd,
# acn, acs, ce and pv, which are one 2004 engine's analysis of the position
# rather than the position.
#
# Changing a line changes every pass count this suite has ever printed,
# so add to the end rather than edit.
"""


def split_operations(text: str) -> list[str]:
    """The `;` separated operations of an epd line, with the separators inside
    a quoted operand left alone."""
    operations = []
    current = ""
    quoted = False
    for character in text:
        if character == '"':
            quoted = not quoted
        if character == ";" and not quoted:
            operations.append(current)
            current = ""
        else:
            current += character
    operations.append(current)
    return [operation.strip() for operation in operations if operation.strip()]


def operations_of(text: str) -> dict[str, str]:
    """The operations of an epd line as opcode to operand."""
    found = {}
    for operation in split_operations(text):
        opcode, _, operand = operation.partition(" ")
        found[opcode] = operand.strip()
    return found


def positions(text: str) -> Iterator[tuple[int, str, dict[str, str]]]:
    """Yield `(line number, four field fen, operations)` for every position in
    an epd file, skipping comments and blank lines."""
    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split(None, 4)
        if len(fields) < 4:
            raise ValueError(f"line {number}: not an epd position: {line}")
        operations = operations_of(fields[4]) if len(fields) > 4 else {}
        yield number, " ".join(fields[:4]), operations


def convert(text: str) -> list[str]:
    """Convert a san suite to epd lines whose bm moves are coordinate moves.

    Anything that will not parse raises rather than being skipped: a move, a
    fen, a position with no bm or no id. A suite that quietly drops the
    positions it could not read gates on a number that means something other
    than what it claims -- "241 of 300" would be counting a smaller suite than
    it names -- and the positions missing from it would be the interesting
    ones, since a move that is hard to read tends to sit in a position that is
    hard to search.
    """
    converted = []
    for number, fen, operations in positions(text):
        for opcode in KEPT:
            if not operations.get(opcode):
                raise ValueError(f"line {number}: no {opcode} operation: {fen}")
        try:
            board = chess.Board(f"{fen} 0 1")
        except ValueError as error:
            raise ValueError(
                f"line {number}: cannot read fen {fen}: {error}"
            ) from error
        moves = []
        for san in operations["bm"].split():
            try:
                moves.append(board.parse_san(san).uci())
            except ValueError as error:
                raise ValueError(
                    f"line {number}: {operations['id']}: cannot read bm {san} "
                    f"in {fen}: {error}"
                ) from error
        converted.append(f"{fen} bm {' '.join(moves)}; id {operations['id']};")
    return converted


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="the epd suite to convert")
    parser.add_argument("output", type=Path, help="path of the epd file to write")
    args = parser.parse_args(argv)

    converted = convert(args.source.read_text(encoding="utf-8"))
    header = HEADER.format(url=SOURCE_URL.format(ref=SOURCE_REF))
    args.output.write_text(
        header + "".join(f"{line}\n" for line in converted),
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {len(converted)} positions to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
